# Generated by Django 3.2.7 on 2021-10-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20211011_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
        migrations.AddField(
            model_name='cart',
            name='total_all',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
