# Generated by Django 3.2.8 on 2021-10-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cart_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_all',
        ),
        migrations.AlterField(
            model_name='cart',
            name='name',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
