# Generated by Django 3.2.8 on 2021-10-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20211030_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
