# Generated by Django 3.2.8 on 2021-10-31 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_cartitem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
