# Generated by Django 3.2.8 on 2021-10-31 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_cart_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['name']},
        ),
    ]
