# Generated by Django 3.2.8 on 2021-11-23 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211123_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cart_id',
        ),
    ]
