# Generated by Django 3.2.8 on 2021-10-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ship',
            field=models.FloatField(default=30000),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='total_all',
            field=models.FloatField(default=0),
        ),
    ]
