# Generated by Django 3.2.8 on 2021-10-31 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
