# Generated by Django 3.2.8 on 2021-10-31 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ship',
            field=models.FloatField(default=1.9),
        ),
    ]
